FROM apache/airflow:2.9.1

# Switch to root to install dependencies
USER root

RUN apt-get update && apt-get install -y docker.io docker-compose-plugin

USER airflow
# Copy requirements.txt to the image
COPY requirements.txt /requirements.txt
# Install Python dependencies
RUN pip install --no-cache-dir -r /requirements.txt

# Copy helpers 
COPY ./src/helpers /opt/airflow/src/helpers
COPY ./src/config /opt/airflow/src/config

ENV PYTHONPATH="/opt/airflow/src:$PYTHONPATH"